### ISSUE TITLE
Definir el código a usar para cada Provincia

### ISSUE THREAD

**Issue by barbanet** [holamugar/module-argentina-regions#1]
Siendo que el módulo aún no está siendo usado, ¿deberíamos quizás cambiar el código del módulo para que use [ISO-3166-2](https://es.wikipedia.org/wiki/ISO_3166-2:AR) y así integrarse mejor con módulos de logística?

**Comment by manuelcanepa** [comment]
Como regla general, yo opino que siempre deberian aplicarse los códigos ISO.

**Comment by barbanet** [comment]
Siendo que sólo tuvo [3 instalaciones (de prueba)](https://packagist.org/packages/mugar/module-argentinaregions) quizás es un buen momento para hacer el fork y cambiar los códigos y ya generar la versión 1.1.0 (¿o la 1.0.1?)

**Comment by manuelcanepa** [comment]
¿Que clase de fork? ¿No se deberia cambiar en este mismo repo? En cuanto a la version, creo que es un cambio un poco mas grande que un fix, asi que 1.1.0 es mas acertado.

**Comment by barbanet** [comment]
Según hemos definido, es vía fork: https://www.mugar.io/como-contribuir-con-los-modulos/
Estoy de acuerdo con lo de la versión.
