### ISSUE TITLE
Preparar readme.md y dejarlo como modelo para otros módulos MugAr

### ISSUE THREAD

**Issue by barbanet** [holamugar/module-argentina-regions#2]
Uno de los temas propuestos para los módulos fue el de tener un readme.md standard para los módulos, de forma tal que cuando cualquier developer o usuario llegue al módulo, siguiendo las instrucciones, pueda hacer uso del módulo.
En el meetup #8 se conversó nuevamente al respecto y se mencionó de usar como punto de partida https://github.com/AOEpeople/Magento-2-Module-Skeleton/blob/master/src/doc/README.template.md, pero simplificandolo considerablemente.

Podríamos aprovechar este módulo para definirlo.

**Comment by dsueiro** [comment]
No veo tanto para sacar salvo las secciones

- Related Projects / tickets / stories
- Build with
- Acknowledgements

**Comment by barbanet** [comment]
Dejé un modelo en el repositorio para revisar en la grooming del 01/02.
